# -*- coding: utf-8 -*-
"""
TwinMOS Corporate Website — Prototype Builder (orchestrator)
Assembles the modules: pb_images (assets) + pb_model (products) + pb_templates
(chrome) + pb_pages (builders) + site_content (facts). Run:  python build.py
"""
import hashlib, json, os, re, sys
from pathlib import Path

import site_content as SC
import pb_images as PI
import pb_model
import pb_templates as T
import pb_pages
import pb_content

# All output paths derive from this file's own directory (local base, literal joins).
OUT_DIR = os.path.dirname(os.path.abspath(__file__))

# Local literal whitelist — every page this builder is allowed to create/verify.
PAGES = ('index.html', 'shop.html', 'product.html', 'compatibility.html', 'compare.html',
         'where-to-buy.html', 'gaming.html', 'solutions.html', 'support.html', 'rma.html', 'learn.html',
         'learn-guides.html', 'learn-explained.html', 'learn-benchmarks.html', 'learn-glossary.html',
         'learn-blog.html',
         'news.html', 'article.html', 'technology.html', 'about.html', 'careers.html', 'contact.html',
         'quote.html', 'legal.html', 'partners.html', 'search.html', '404.html', 'sitemap.html')

def write_data_js(products):
    articles = [dict(a, img=SC.ARTICLE_IMGS.get(a.get('id'), a.get('img', ''))) for a in SC.ARTICLES]
    data = {
        'products': products,
        'categories': [{'id': cid, 'label': label} for cid, label in SC.CATS],
        'articles': articles,
        'compat': SC.COMPAT_DB,
        'glossary': getattr(SC, 'GLOSSARY', []),
    }
    js = ('/* Generated by build.py — catalog data + content library */\n'
          'window.TM = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')
    Path(os.path.join(OUT_DIR, 'assets', 'js', 'data.js')).write_text(js, encoding='utf-8')
    print('  wrote assets/js/data.js', len(js), 'bytes')

def write_manifest():
    man = {
        'name': 'TwinMOS Technologies', 'short_name': 'TwinMOS',
        'description': 'Memory & storage solutions since 1998 — TwinMOS corporate site prototype',
        'start_url': 'index.html', 'display': 'standalone', 'background_color': '#FFFFFF',
        'theme_color': '#0A2540',
        'icons': [
            {'src': 'assets/img/icon-192.png', 'sizes': '192x192', 'type': 'image/png'},
            {'src': 'assets/img/icon-512.png', 'sizes': '512x512', 'type': 'image/png'},
        ],
    }
    Path(os.path.join(OUT_DIR, 'manifest.webmanifest')).write_text(
        json.dumps(man, ensure_ascii=False, indent=1), encoding='utf-8')
    pages_csv = ','.join("'%s'" % p for p in PAGES)
    av = T.ASSET_V
    sw = ("// TwinMOS prototype service worker — network-first pages, cache-first versioned assets\n"
          "var CACHE = 'twinmos-proto-' + '" + av + "';\n"
          "var ASSETS = [" + pages_csv + ",'assets/css/main.css?v=" + av + "','assets/js/app.js?v=" + av + "','assets/js/data.js?v=" + av + "','assets/img/logo.webp?v=" + av + "'];\n"
          "self.addEventListener('install', function (e) {\n"
          "  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); }).then(function () { return self.skipWaiting(); }));\n"
          "});\n"
          "self.addEventListener('activate', function (e) {\n"
          "  e.waitUntil(caches.keys().then(function (keys) {\n"
          "    return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));\n"
          "  }).then(function () { return self.clients.claim(); }));\n"
          "});\n"
          "self.addEventListener('fetch', function (e) {\n"
          "  if (e.request.method !== 'GET') return;\n"
          "  var url = new URL(e.request.url);\n"
          "  if (e.request.mode === 'navigate' || url.pathname.endsWith('.html') || url.pathname === '/') {\n"
          "    // pages: network-first so rebuilds are picked up immediately; cache only as offline fallback\n"
          "    e.respondWith(fetch(e.request).then(function (r) {\n"
          "      var cp = r.clone(); caches.open(CACHE).then(function (c) { c.put(e.request, cp); });\n"
          "      return r;\n"
          "    }).catch(function () { return caches.match(e.request).then(function (hit) { return hit || caches.match('index.html'); }); }));\n"
          "    return;\n"
          "  }\n"
          "  // content-hashed (?v=) assets are immutable → cache-first; anything else falls through to network\n"
          "  e.respondWith(caches.match(e.request).then(function (hit) { return hit || fetch(e.request); }));\n"
          "});\n")
    Path(os.path.join(OUT_DIR, 'sw.js')).write_text(sw, encoding='utf-8')
    print('  wrote manifest.webmanifest + sw.js')

def flush_pages():
    """Write every rendered page from the registry, iterating the literal whitelist."""
    for fname in PAGES:
        doc = T.PAGES_OUT.get(fname)
        if doc is None:
            raise RuntimeError('missing rendered page: ' + fname)
        Path(os.path.join(OUT_DIR, fname)).write_text(doc, encoding='utf-8')
    print('  flushed %d pages to disk' % len(PAGES))

def known_output_files():
    """Set of every file inside the prototype as relative forward-slash paths."""
    found = set()
    for base, dirs, files in os.walk(OUT_DIR):
        for fn in files:
            found.add(os.path.relpath(os.path.join(base, fn), OUT_DIR).replace(os.sep, '/'))
    return found

def qa(products):
    print('\n=== QA: links & assets ===')
    issues = []
    known = known_output_files()
    for pf in PAGES:  # literal whitelist iteration
        if pf not in known:
            issues.append('page not generated: ' + pf)
            continue
        with open(os.path.join(OUT_DIR, pf), encoding='utf-8') as f:
            doc = f.read()
        for ref in re.findall(r'(?:href|src)="([^"#]+)"', doc):
            if ref.startswith(('http', 'mailto:', 'data:', 'javascript')) or not ref:
                continue
            target = ref.split('?')[0]
            if target and target not in known:
                issues.append('%s -> missing %s' % (pf, ref))
    for p in products:
        if not p['img']:
            issues.append('product %s has no image' % p['id'])
        for g in p['gallery']:
            if g not in known:
                issues.append('product %s gallery missing %s' % (p['id'], g))
        if p.get('imgC') and p['imgC'] not in known:
            issues.append('product %s card variant missing %s' % (p['id'], p['imgC']))
    if issues:
        print('  ISSUES (%d):' % len(issues))
        for i in issues[:40]:
            print('   -', i)
    else:
        print('  all internal links + asset references resolve OK')
    return issues

def set_asset_version():
    """Cache-bust css/js by content hash so every rebuild ships a fresh URL."""
    h = hashlib.sha256()
    for rel in ('assets/css/main.css', 'assets/js/app.js', 'assets/js/data.js'):
        p = os.path.join(OUT_DIR, rel)
        if os.path.isfile(p):
            h.update(Path(p).read_bytes())
    T.ASSET_V = h.hexdigest()[:10]
    print('  asset version:', T.ASSET_V)

def main():
    print('TwinMOS prototype builder')
    print('  workspace root:', PI.WS)
    print('  Pillow:', PI.HAVE_PIL)
    PI.ensure_dirs()

    products = pb_model.load_products()
    print('  products normalized:', len(products))

    # merge the content corpus (learn hub / KB / FAQs) into site_content
    pb_content.enrich(SC)

    missing = PI.import_curated()
    for name in missing:
        print('  [warn] curated asset missing:', name)

    # regenerate the transparent-background logo BEFORE any page references it
    PI.make_transparent_logo()

    # bake blended hero banners (one image per slide; mutates slide dicts in place)
    PI.bake_hero_banners(SC.HOME_SLIDES, 'home')
    PI.bake_hero_banners(SC.GAMING_SLIDES, 'gaming')

    # trimmed card variants: grids render the product, not its square canvas
    card_rels = set()
    for p in products:
        if p.get('img'):
            card_rels.add(p['img'])
        for g in (p.get('gallery') or []):
            card_rels.add(g)
    for tile in SC.CAT_TILES:
        card_rels.add('assets/img/' + tile[3])
    PI.make_card_variants(sorted(card_rels))
    for p in products:
        p['imgC'] = 'assets/img/card/' + os.path.basename(p['img']) if p.get('img') else ''
        p['galleryC'] = ['assets/img/card/' + os.path.basename(g) for g in (p.get('gallery') or [])]

    # article heroes: bake wide banners from the trimmed cutouts (no more cover-crops)
    SC.ARTICLE_IMGS = PI.bake_article_heroes(SC.ARTICLE_IMGS)

    # gaming hub wallpapers: real downloadable assets baked from the same palette
    SC.WALLPAPERS = PI.make_gaming_wallpapers()

    write_data_js(products)          # data.js first so its bytes feed the hash
    set_asset_version()

    print('\n=== rendering pages ===')
    pb_pages.build_all(products)
    flush_pages()
    write_manifest()
    PI.make_icons()

    issues = qa(products)
    print('\nDone. %d HTML pages.' % len(PAGES))
    return 0 if not issues else 1

if __name__ == '__main__':
    sys.exit(main())
