// P3 content exporter — regenerates apps/web/public/assets/js/cms-content.js
// from the DB (published + due only). The site merge layer (cms-merge.js) adds
// ONLY slugs not already present in the prototype data.js, so a corpus import
// can never duplicate what the prototype already renders — parity by design.
// Run from repo root:  node --experimental-strip-types --no-warnings tooling/export-content.mjs
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDb, article, newsPost, faq } from './db-bridge.ts';

const HERE = dirname(fileURLToPath(import.meta.url)); // .../twinmso_codebase/tooling
const OUT = join(HERE, '..', 'apps', 'web', 'public', 'assets', 'js', 'cms-content.js');

const db = createDb();
const now = new Date();

const arts = await db.select().from(article);
const news = await db.select().from(newsPost);
const faqs = await db.select().from(faq);

// Build-time slug-diff against the prototype data.js (synced by the prebuild
// before this runs): anything the prototype already renders is EXCLUDED, so
// cms-content.js stays tiny (only genuinely new CMS content) and parity plus
// Lighthouse gates are unaffected.
function prototypeIds() {
  try {
    const src = readFileSync(join(HERE, '..', 'apps', 'web', 'public', 'assets', 'js', 'data.js'), 'utf8');
    const ids = new Set();
    for (const m of src.matchAll(/"id":"([^"]{2,120})"/g)) ids.add(m[1]);
    return ids;
  } catch {
    return new Set(); // data.js not synced yet — export everything (runtime merge still guards)
  }
}
const known = prototypeIds();

const published = (rows, entity) => rows
  .filter((r) => r.status === 'published' && !r.deletedAt && (!r.publishAt || new Date(r.publishAt) <= now))
  .filter((r) => !known.has(r.slug)) // prototype already renders it — skip
  .map((r) => ({
    id: entity + '-' + r.id,
    slug: r.slug,
    title: r.title,
    deck: r.deck ?? (r.tag ?? ''),
    cat: entity === 'news' ? (r.eventDate ? 'Event' : 'News') : r.category,
    tag: r.tag ?? null,
    eventDate: r.eventDate ?? null,
    date: r.publishAt ?? r.createdAt,
    body: r.body,
    source: 'cms',
  }));

// FAQs are admin/support-facing (not consumed by the site merge layer) —
// excluded here so the shipped file carries only what the site renders.
const faqItems = [];

const payload = `/* AUTO-GENERATED by tooling/export-content.mjs — CMS content for the website.
 * The merge layer only adds slugs ABSENT from the prototype data.js (no duplication). */
window.CMS_CONTENT = ${JSON.stringify({
  articles: published(arts, 'article'),
  news: published(news, 'news'),
  faqs: faqItems,
  generatedAt: now.toISOString(),
}, null, 0)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, payload, 'utf8');
console.log(`[export-content] cms-content.js: articles=${published(arts, 'article').length} news=${published(news, 'news').length} faqs=${faqItems.length}`);
await db.$client.close();
