#!/usr/bin/env python3
"""Generate apps/web/public/assets/js/pdp-hero.js — a productId -> hero image
map extracted from the ported data.js. The Layout's preload snippet loads this
at parse-end and fetchpriority-hints the hero for ?id= deep links, so the PDP
LCP image is discovered ~3s earlier than the app-layer render would.

Run from repo root:  python tooling/gen_pdp_hero.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "apps" / "web" / "public" / "assets" / "js" / "data.js"
OUT = REPO / "apps" / "web" / "public" / "assets" / "js" / "pdp-hero.js"

ENTRY = re.compile(r'"id":"([^"]+)"[^{}]*?"img":"([^"]+)"')


def main() -> int:
    src = DATA.read_text(encoding="utf-8")
    pairs: dict[str, str] = {}
    for mid, img in ENTRY.findall(src):
        pairs.setdefault(mid, img)  # first img after each id wins
    payload = (
        "/* AUTO-GENERATED by tooling/gen_pdp_hero.py — product id -> hero image. */\n"
        "window.PDP_HERO = " + json.dumps(pairs, separators=(",", ":")) + ";\n"
    )
    OUT.write_text(payload, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} with {len(pairs)} products")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
