#!/usr/bin/env python3
"""Generate apps/web/public/assets/js/img-dims.js — a filename -> (w,h) map of
all card/banner imagery. Consumed by a11y.js to set width/height attributes on
JS-inserted <img> tags at insertion time (before load), which reserves the
correct layout box and eliminates CLS. Visual output is unchanged.

Run from repo root:  python tooling/gen_img_dims.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
WEB = REPO / "apps" / "web"
IMG_DIRS = ["assets/img/card", "assets/img/bn", "assets/img/pdp"]
OUT_JS = WEB / "public" / "assets" / "js" / "img-dims.js"


def main() -> int:
    dims: dict[str, list[int]] = {}
    for rel in IMG_DIRS:
        root = WEB / "public" / rel
        if not root.is_dir():
            print(f"skip missing {rel}")
            continue
        for f in sorted(root.iterdir()):
            if f.suffix.lower() not in {".webp", ".png", ".jpg", ".jpeg"}:
                continue
            try:
                with Image.open(f) as im:
                    dims[f"{rel}/{f.name}"] = list(im.size)
            except Exception as e:  # noqa: BLE001 - report and continue
                print(f"unreadable {f.name}: {e}", file=sys.stderr)
    payload = (
        "/* AUTO-GENERATED by tooling/gen_img_dims.py — intrinsic sizes for "
        "CLS-safe width/height attributes. Do not edit by hand. */\n"
        "window.IMG_DIMS = " + json.dumps(dims, separators=(",", ":")) + ";\n"
    )
    OUT_JS.write_text(payload, encoding="utf-8")
    print(f"wrote {OUT_JS.relative_to(REPO)} with {len(dims)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
