#!/usr/bin/env python3
"""Generates public/sitemap.xml from the ported page list (P1 URL scheme: /page.html).

P3.4 (audit, Tier-3): the sitemap previously listed only the 28 page shells +
locale landings. It now also emits the deep URLs real visitors land on, read
from the CMS content bridge (cms-content.js) so catalog/article/news pages
created in the console become discoverable:
  - product.html?id=<slug>          for every bridged product
  - article.html?id=<slug>          for every bridged article/news item
The bridge file is regenerated by the exporter (CLI or POST /admin/content/
export); if it is absent or empty the sitemap degrades to page shells only.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PAGES_DIR = REPO / 'apps' / 'web' / 'src' / 'pages'
BRIDGE = REPO / 'apps' / 'web' / 'public' / 'assets' / 'js' / 'cms-content.js'
SITE = 'https://www.twinmos.com/'
PRIORITY = {'index.html': ('1.0', 'daily'), 'shop.html': ('0.9', 'daily'), 'product.html': ('0.9', 'weekly'),
            'support.html': ('0.9', 'weekly'), 'learn.html': ('0.9', 'weekly'), '404.html': None}


def load_bridge():
    """Parse window.CMS_CONTENT = {...}; from the bridge (no JS engine needed)."""
    if not BRIDGE.exists():
        return None
    src = BRIDGE.read_text(encoding='utf-8')
    start = src.find('window.CMS_CONTENT')
    if start < 0:
        return None
    brace = src.find('{', start)
    if brace < 0:
        return None
    depth, in_str, esc = 0, None, False
    for i in range(brace, len(src)):
        ch = src[i]
        if in_str:
            if esc:
                esc = False
            elif ch == '\\':
                esc = True
            elif ch == in_str:
                in_str = None
            continue
        if ch in ('"', "'"):
            in_str = ch
        elif ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(src[brace:i + 1])
                except json.JSONDecodeError:
                    return None
    return None


def main() -> int:
    urls = []
    for f in sorted(PAGES_DIR.glob('*.astro')):
        page = f.stem + '.html'
        spec = PRIORITY.get(page, ('0.7', 'weekly'))
        if spec is None:
            continue  # 404 not listed
        # homepage is the site root, matching the canonical in Layout.astro
        loc = SITE if page == 'index.html' else SITE + page
        urls.append(f'  <url><loc>{loc}</loc><changefreq>{spec[1]}</changefreq><priority>{spec[0]}</priority></url>')
    # P4 locale landings (/{code}.html from the [locale] dynamic route) —
    # discoverable alternates of the homepage; lower priority than the EN root.
    for code in ('ar', 'hi', 'ru', 'zh-cn', 'fr', 'es', 'pt', 'de'):
        urls.append(f'  <url><loc>{SITE}{code}.html</loc><changefreq>weekly</changefreq><priority>0.6</priority></url>')

    # ---- P3.4: deep content URLs from the CMS bridge -----------------------
    bridge = load_bridge()
    deep = 0
    if bridge:
        slug_re = re.compile(r'^[a-z0-9-]{2,120}$')
        for p in bridge.get('products') or []:
            slug = p.get('slug')
            if slug and slug_re.match(str(slug)):
                urls.append(f'  <url><loc>{SITE}product.html?id={slug}</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>')
                deep += 1
        for kind in ('articles', 'news'):
            for a in bridge.get(kind) or []:
                slug = a.get('slug')
                if slug and slug_re.match(str(slug)):
                    urls.append(f'  <url><loc>{SITE}article.html?id={slug}</loc><changefreq>monthly</changefreq><priority>0.6</priority></url>')
                    deep += 1

    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + '\n'.join(urls) + '\n</urlset>\n'
    out = REPO / 'apps' / 'web' / 'public' / 'sitemap.xml'
    out.write_text(xml, encoding='utf-8', newline='\n')
    print(f'[sitemap] {len(urls)} urls ({deep} deep content) -> {out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
