#!/usr/bin/env python3
"""P1 page porter — generates one .astro page per prototype HTML page.

Strategy (docs/05-PROTOTYPE-MIGRATION.md, parity-first variant):
  Layout.astro owns the document shell (head + body wrapper + data.js/app.js).
  Each generated page carries the prototype's <body> inner HTML VERBATIM
  (header, breadcrumb, main, footer — exactly what shipped in the audited
  prototype), so visual + behavioral parity hold by construction.

Read-only against the prototype (immutable reference). Output: apps/web/src/pages/*.astro
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PROTO = REPO.parent / 'Corporate website development for TwinMOS' / 'Features' / 'prototype'
OUT = REPO / 'apps' / 'web' / 'src' / 'pages'

TITLE_RE = re.compile(r'<title>(.*?)</title>', re.S)
DESC_RE = re.compile(r'<meta name="description" content="([^"]*)"', re.S)
BODY_TAG_RE = re.compile(r'<body([^>]*)>')
BODY_RE = re.compile(r'<body[^>]*>(.*)</body>', re.S)
TRAILING_SCRIPTS_RE = re.compile(
    r'<script src="assets/js/data\.js[^"]*"></script>\s*'
    r'<script src="assets/js/app\.js[^"]*"></script>\s*$', re.S)
CLASS_RE = re.compile(r'class="([^"]*)"')

TEMPLATE = '''---
// GENERATED by tooling/port_pages.py from ../prototype/{src} — do not hand-edit.
// Regenerate with: python tooling/port_pages.py
import Layout from '../layouts/Layout.astro';
const title = {title};
const desc = {desc};
const bodyClass = {body_class};
const noindex = {noindex};
const bodyHtml = {body_html};
---
<Layout title={{title}} desc={{desc}} bodyClass={{bodyClass}} noindex={{noindex}}>
  <Fragment set:html={{bodyHtml}} />
</Layout>
'''


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    pages = sorted(PROTO.glob('*.html'))
    if len(pages) < 20:
        print(f'!! only {len(pages)} pages found under {PROTO} — aborting'); return 1
    written = []
    for src in pages:
        html = src.read_text(encoding='utf-8')
        title_m = TITLE_RE.search(html)
        desc_m = DESC_RE.search(html)
        body_tag_m = BODY_TAG_RE.search(html)
        body_m = BODY_RE.search(html)
        if not (title_m and desc_m and body_m):
            print(f'!! {src.name}: missing title/desc/body — skipped'); return 1
        body_inner = TRAILING_SCRIPTS_RE.sub('', body_m.group(1))
        cls_m = CLASS_RE.search(body_tag_m.group(1)) if body_tag_m else None
        ctx = {
            'title': json.dumps(title_m.group(1)),
            'desc': json.dumps(desc_m.group(1)),
            'body_class': json.dumps(cls_m.group(1) if cls_m else ''),
            'noindex': 'true' if src.name == '404.html' else 'false',
            'body_html': json.dumps(body_inner),
            'src': src.name,
        }
        (OUT / f'{src.stem}.astro').write_text(TEMPLATE.format(**ctx), encoding='utf-8', newline='\n')
        written.append(src.name)
    print(f'[port] {len(written)} pages -> {OUT}')
    for name in written:
        print('  -', name)
    return 0


if __name__ == '__main__':
    sys.exit(main())
